"""
apps.forecasting.services
─────────────────────────────────────────────────────────────────────────────
AutoPODraftingService — Reads DemandPrediction records and creates Draft POs
                        in apps.procurement when stockout date is within
                        the supplier's lead time window.
─────────────────────────────────────────────────────────────────────────────
"""
import uuid
import logging
from decimal import Decimal
from datetime import date, timedelta
from typing import Optional

from django.db import transaction

logger = logging.getLogger(__name__)


class AutoPODraftingService:
    """
    Reads DemandPrediction records flagged as PENDING and creates Draft
    PurchaseOrders in apps.procurement for the Sourcing Manager to review.

    Called by the Celery task `generate_draft_pos` (Step 6).
    Also available via POST /forecasting/draft-pos/generate/ for on-demand runs.
    """

    @classmethod
    @transaction.atomic
    def generate_for_prediction(
        cls,
        prediction_id: uuid.UUID,
        actor_id: Optional[uuid.UUID] = None,
    ) -> Optional["PurchaseOrder"]:  # type: ignore
        """
        Creates a Draft PO for a single DemandPrediction if the stockout
        date is within the supplier's lead time window.

        Returns the created PurchaseOrder or None if not actionable.
        """
        from apps.forecasting.models import DemandPrediction, PredictionStatus
        from apps.procurement.models import PurchaseOrder, POLineItem

        prediction = DemandPrediction.objects.select_for_update().get(id=prediction_id)

        if prediction.status != PredictionStatus.PENDING:
            logger.info(
                "Prediction '%s' already processed (status: %s). Skipping.",
                prediction_id,
                prediction.status,
            )
            return None

        product = prediction.product
        days_until_stockout = (prediction.projected_stockout_date - date.today()).days
        lead_days = product.supplier_lead_days

        if days_until_stockout > lead_days:
            logger.info(
                "Prediction '%s': stockout in %d days, lead time %d days. "
                "No Draft PO needed yet.",
                prediction_id,
                days_until_stockout,
                lead_days,
            )
            return None  # Not urgent enough to draft a PO

        logger.info(
            "AutoPO trigger: '%s' stockout in %d days (lead: %d). "
            "Drafting PO for %d units.",
            product.sku_code,
            days_until_stockout,
            lead_days,
            prediction.recommended_reorder_qty,
        )

        # Calculate estimated total cost using current MAC.
        unit_cost = product.moving_average_cost or Decimal("0")
        total_cost = unit_cost * Decimal(prediction.recommended_reorder_qty)

        # Create Draft PurchaseOrder.
        po = PurchaseOrder.objects.create(
            vendor_name=f"Auto-Draft: {product.sku_code} supplier",
            total_cost=total_cost,
            notes=(
                f"Auto-generated by ForecastingEngine. "
                f"Stockout projected: {prediction.projected_stockout_date}. "
                f"Lead days: {lead_days}."
            ),
            expected_delivery_date=date.today() + timedelta(days=lead_days),
        )

        # Create PO line item.
        POLineItem.objects.create(
            po=po,
            product=product,
            ordered_qty=prediction.recommended_reorder_qty,
            unit_cost=unit_cost,
        )

        # Update prediction status.
        prediction.status = PredictionStatus.DRAFT_PO_GENERATED
        prediction.draft_po_id = po.id
        prediction.save(update_fields=["status", "draft_po_id"])

        logger.info(
            "Draft PO '%s' created for prediction '%s' (%d × %s).",
            po.id,
            prediction_id,
            prediction.recommended_reorder_qty,
            product.sku_code,
        )
        return po

    @classmethod
    def generate_all_pending(cls, actor_id: Optional[uuid.UUID] = None) -> dict:
        """
        Processes all PENDING DemandPrediction records.
        Called by the nightly Celery beat task.
        """
        from apps.forecasting.models import DemandPrediction, PredictionStatus

        pending = DemandPrediction.objects.filter(
            status=PredictionStatus.PENDING
        ).values_list("id", flat=True)

        results = {"processed": 0, "drafted": 0, "skipped": 0, "errors": 0}

        for pred_id in pending:
            try:
                po = cls.generate_for_prediction(pred_id, actor_id=actor_id)
                if po:
                    results["drafted"] += 1
                else:
                    results["skipped"] += 1
                results["processed"] += 1
            except Exception as exc:
                logger.error(
                    "AutoPO failed for prediction '%s': %s", pred_id, exc, exc_info=True
                )
                results["errors"] += 1

        logger.info("AutoPODraftingService.generate_all_pending() complete: %s", results)
        return results
