# Generated by Django 6.0.6 on 2026-06-29 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_index=True, help_text="The Django model table name, e.g., 'inventory_productsku'.", max_length=100)),
                ('record_id', models.UUIDField(db_index=True, help_text='The UUID primary key of the mutated record.')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10)),
                ('before_state', models.JSONField(blank=True, help_text='Full model state BEFORE the mutation (null for CREATE actions).', null=True)),
                ('after_state', models.JSONField(blank=True, help_text='Full model state AFTER the mutation (null for DELETE actions).', null=True)),
                ('actor_id', models.UUIDField(db_index=True, help_text='UUID of the GlobalUser who triggered the mutation.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP address of the actor's request for forensic analysis.", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Commit',
                'verbose_name_plural': 'Audit Commits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['table_name', 'timestamp'], name='audit_table_ts_idx'), models.Index(fields=['actor_id', 'timestamp'], name='audit_actor_ts_idx'), models.Index(fields=['record_id'], name='audit_record_id_idx')],
            },
        ),
    ]
