# Generated by Django 6.0.6 on 2026-06-29 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(db_index=True, help_text="Unique product identifier (e.g., 'SKU-ELEC-001').", max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('weight_kg', models.DecimalField(decimal_places=4, default=0, help_text='Unit weight in kilograms. Used by FleetCapacityService.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_m3', models.DecimalField(decimal_places=6, default=0, help_text='Unit volume in cubic metres. Used for truck loading calculations.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_hazmat', models.BooleanField(db_index=True, default=False, help_text='If True, the HazmatGeofenceService will block put-away to any BinLocation with zone_type != HAZMAT.')),
                ('moving_average_cost', models.DecimalField(decimal_places=4, default=0, help_text='Weighted moving average unit cost. Updated by ValuationEngine on each PO receipt.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_point', models.IntegerField(default=0, help_text='Minimum stock level that triggers a forecasting alert.', validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier_lead_days', models.IntegerField(default=7, help_text='Average supplier lead time. Used by AutoPODraftingService.', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product SKU',
                'verbose_name_plural': 'Product SKUs',
                'ordering': ['sku_code'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta_quantity', models.IntegerField(help_text='Signed integer representing the stock change. +500 for inbound receipt. -20 for outbound delivery.')),
                ('unit_cost_at_time', models.DecimalField(blank=True, decimal_places=4, help_text='The unit cost at time of this delta (used for FIFO valuation).', max_digits=14, null=True)),
                ('reference_module', models.CharField(choices=[('procurement', 'Procurement (PO Receipt)'), ('logistics', 'Logistics (Delivery)'), ('returns', 'Returns (Restock)'), ('adjustment', 'Manual Cycle Count Adjustment'), ('forecasting', 'Forecasting (Initial Stock)')], db_index=True, help_text='Which module triggered this stock movement.', max_length=20)),
                ('reference_id', models.UUIDField(db_index=True, help_text='UUID of the source document (PO, SalesOrder, RMA, etc.).')),
                ('notes', models.CharField(blank=True, default='', help_text='Optional human-readable reason (mandatory for manual adjustments).', max_length=500)),
                ('created_by_actor_id', models.UUIDField(blank=True, help_text='UUID of the GlobalUser who triggered this ledger entry.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(help_text='The product this delta applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.productsku')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='stock_product_ts_idx'), models.Index(fields=['reference_module', 'reference_id'], name='stock_ref_idx')],
            },
        ),
    ]
