# Generated by Django 6.0.6 on 2026-06-30 06:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='is_hazmat',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='moving_average_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='reorder_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='sku_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='supplier_lead_days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='volume_m3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='weight_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='created_by_actor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='delta_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.productsku'),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='reference_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='reference_module',
            field=models.CharField(choices=[('procurement', 'Procurement'), ('logistics', 'Logistics'), ('returns', 'Returns'), ('adjustment', 'Adjustment'), ('forecasting', 'Forecasting')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='unit_cost_at_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
