# Generated by Django 6.0.6 on 2026-06-29 11:15

import apps.warehouse.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinate_string', models.CharField(db_index=True, help_text='Unique 3D location string. Format: ZONE-AISLE-RACK-LEVEL-BIN. Example: DRY-01-12-3-B', max_length=30, unique=True, validators=[apps.warehouse.models.validate_coordinate_string])),
                ('zone_type', models.CharField(choices=[('DRY', 'Dry Storage'), ('COLD', 'Cold Storage'), ('HAZMAT', 'Hazardous Materials'), ('RETURNS', 'Returns / Quarantine')], db_index=True, max_length=10)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, help_text='Maximum allowable weight for this bin in kilograms.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive bins are excluded from pick-path generation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bin Location',
                'verbose_name_plural': 'Bin Locations',
                'ordering': ['coordinate_string'],
                'indexes': [models.Index(fields=['zone_type', 'coordinate_string'], name='bin_zone_coord_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_qty', models.IntegerField(default=0, help_text='Current units of this product physically located in this bin.', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='warehouse.binlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_positions', to='inventory.productsku')),
            ],
            options={
                'verbose_name': 'Inventory Position',
                'verbose_name_plural': 'Inventory Positions',
                'indexes': [models.Index(fields=['product', 'current_qty'], name='inv_pos_product_qty_idx')],
                'unique_together': {('bin', 'product')},
            },
        ),
    ]
