# Generated by Django 6.0.6 on 2026-06-29 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projected_stockout_date', models.DateField(db_index=True, help_text='Date when current stock is projected to reach zero.')),
                ('recommended_reorder_qty', models.IntegerField(help_text='Quantity the AutoPODraftingService will put on the Draft PO.')),
                ('analysis_window_days', models.IntegerField(default=90, help_text='Number of historical days analysed by the Pandas worker.')),
                ('average_daily_demand', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated average units consumed per day.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('DRAFT_PO_GENERATED', 'Draft PO Generated'), ('IGNORED', 'Ignored by Sourcing Manager')], db_index=True, default='PENDING', max_length=25)),
                ('draft_po_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of the PurchaseOrder created in DRAFT status.', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this prediction was calculated.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_predictions', to='inventory.productsku')),
            ],
            options={
                'verbose_name': 'Demand Prediction',
                'verbose_name_plural': 'Demand Predictions',
                'ordering': ['projected_stockout_date'],
                'indexes': [models.Index(fields=['product', 'status'], name='forecast_product_status_idx')],
            },
        ),
    ]
