# Generated by Django 6.0.6 on 2026-06-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
        ('inventory', '0002_auto_schema_fix'),
        ('procurement', '0002_auto_schema_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandprediction',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Demand Prediction', 'verbose_name_plural': 'Demand Predictions'},
        ),
        migrations.RemoveIndex(
            model_name='demandprediction',
            name='forecast_product_status_idx',
        ),
        migrations.AddField(
            model_name='demandprediction',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Model confidence 0.00–100.00.', max_digits=5),
        ),
        migrations.AddField(
            model_name='demandprediction',
            name='draft_po',
            field=models.ForeignKey(blank=True, help_text='The auto-generated Draft PO linked to this prediction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_predictions', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='demandprediction',
            name='model_used',
            field=models.CharField(blank=True, default='', help_text="Algorithm identifier, e.g., 'ARIMA', 'Prophet', 'ExponentialSmoothing'.", max_length=50),
        ),
        migrations.AddField(
            model_name='demandprediction',
            name='suggested_order_qty',
            field=models.IntegerField(default=0, help_text='Recommended reorder quantity to cover lead time + safety stock.'),
        ),
        migrations.AlterField(
            model_name='demandprediction',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='demandprediction',
            name='projected_stockout_date',
            field=models.DateField(db_index=True, help_text='Predicted date when stock will reach zero.'),
        ),
        migrations.AlterField(
            model_name='demandprediction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PO_DRAFTED', 'Draft PO Generated'), ('SKIPPED', 'Ignored by Sourcing Manager')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='demandprediction',
            index=models.Index(fields=['projected_stockout_date'], name='forecast_stockout_date_idx'),
        ),
        migrations.RemoveField(
            model_name='demandprediction',
            name='analysis_window_days',
        ),
        migrations.RemoveField(
            model_name='demandprediction',
            name='average_daily_demand',
        ),
        migrations.RemoveField(
            model_name='demandprediction',
            name='draft_po_id',
        ),
        migrations.RemoveField(
            model_name='demandprediction',
            name='recommended_reorder_qty',
        ),
    ]
