# Generated by Django 6.0.6 on 2026-06-29 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('procurement', '0001_initial'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_number', models.CharField(db_index=True, help_text='ISO 6346 container ID, e.g., MSKU1234567.', max_length=50, unique=True)),
                ('ocean_carrier', models.CharField(help_text="Carrier name, e.g., 'Maersk', 'MSC', 'COSCO'.", max_length=100)),
                ('carrier_api_ref', models.CharField(blank=True, default='', help_text='External tracking reference returned by the carrier API.', max_length=200)),
                ('tracking_milestone', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('DEPARTED_ORIGIN', 'Departed Origin Port'), ('IN_TRANSIT', 'In Transit (Open Ocean)'), ('ARRIVED_DESTINATION', 'Arrived at Destination Port'), ('CLEARED_CUSTOMS', 'Cleared Customs'), ('OUT_FOR_DELIVERY', 'Out for Inland Delivery'), ('DELIVERED', 'Delivered to Warehouse')], db_index=True, default='BOOKING_CONFIRMED', max_length=30)),
                ('origin_port', models.CharField(blank=True, default='', max_length=100)),
                ('destination_port', models.CharField(blank=True, default='', max_length=100)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful carrier API poll.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po', models.ForeignKey(help_text='The PurchaseOrder whose goods are in this container.', on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'Inbound Container',
                'verbose_name_plural': 'Inbound Containers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True, help_text='UUID of the GlobalUser (Retail Customer) who placed this order.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PACKING', 'Packing'), ('PACKED', 'Packed and Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('delivery_address', models.CharField(blank=True, default='', max_length=500)),
                ('delivery_gps_coordinate', models.JSONField(default=dict, help_text='{"lat": 34.0522, "lng": -118.2437} — Used by PostGIS routing for DispatchRoute optimization. Production migration adds native GEOMETRY(Point, 4326) column.')),
                ('pod_signature_s3_url', models.CharField(blank=True, help_text="S3 URL of the customer's delivery signature image.", max_length=500, null=True)),
                ('pod_received_by_name', models.CharField(blank=True, default='', help_text='Name of the person who received the delivery.', max_length=255)),
                ('pod_captured_at', models.DateTimeField(blank=True, help_text='Timestamp when ePOD was captured.', null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='transportation.dispatchroute')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='inventory.productsku')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Item',
                'verbose_name_plural': 'Sales Order Items',
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'created_at'], name='so_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer_id'], name='so_customer_idx'),
        ),
    ]
