# Generated by Django 6.0.6 on 2026-06-29 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Primary login credential. Must be unique across all tenants.', max_length=254, unique=True)),
                ('is_superadmin', models.BooleanField(default=False, help_text='SaaS Super Admin — has global platform management access.')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Global User',
                'verbose_name_plural': 'Global Users',
            },
        ),
        migrations.CreateModel(
            name='JwtBlacklistedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, help_text="The 'jti' claim from the JWT payload.", max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklisted JWT Token',
                'verbose_name_plural': 'Blacklisted JWT Tokens',
            },
        ),
        migrations.CreateModel(
            name='TenantUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the Client (Tenant). Validated by the service layer.')),
                ('role', models.CharField(choices=[('ADMIN', 'Enterprise Admin'), ('WAREHOUSE_MGR', 'Warehouse Manager'), ('SOURCING_MGR', 'Sourcing Manager'), ('LOGISTICS_MGR', 'Logistics Manager'), ('ACCOUNTANT', 'Accountant'), ('RETAIL_USER', 'Retail User')], default='RETAIL_USER', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Soft-disable a user's access to a specific tenant.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant User Mapping',
                'verbose_name_plural': 'Tenant User Mappings',
            },
        ),
        migrations.AddIndex(
            model_name='globaluser',
            index=models.Index(fields=['email'], name='users_globaluser_email_idx'),
        ),
        migrations.AddIndex(
            model_name='jwtblacklistedtoken',
            index=models.Index(fields=['jti'], name='users_blacklist_jti_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantusermapping',
            index=models.Index(fields=['user', 'tenant_id'], name='users_mapping_user_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantusermapping',
            index=models.Index(fields=['tenant_id'], name='users_mapping_tenant_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantusermapping',
            unique_together={('user', 'tenant_id')},
        ),
    ]
