# Generated by Django 6.0.6 on 2026-06-29 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMAClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_quantity', models.IntegerField(help_text='Number of units being returned.', validators=[django.core.validators.MinValueValidator(1)])),
                ('disposition_triage', models.CharField(choices=[('PENDING', 'Pending Triage'), ('RESTOCK', 'Restock (Returned to Inventory)'), ('REPAIR', 'Repair (Sent to Repair Bay)'), ('SCRAP', 'Scrap (Write Off Asset)')], db_index=True, default='PENDING', max_length=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to refund to the customer for this return.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('return_reason', models.CharField(blank=True, default='', help_text="Customer's stated reason for the return.", max_length=500)),
                ('triage_notes', models.TextField(blank=True, default='', help_text="Warehouse manager's assessment notes after physical inspection.")),
                ('triaged_by_actor_id', models.UUIDField(blank=True, help_text='UUID of the Warehouse Manager who performed the dock triage.', null=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_label_url', models.CharField(blank=True, default='', help_text='URL to the generated return shipping label.', max_length=500)),
                ('restock_ledger_entry_id', models.UUIDField(blank=True, help_text='UUID of the StockLedger entry created on RESTOCK disposition.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_claims', to='inventory.productsku')),
                ('sales_order', models.ForeignKey(help_text='The original SalesOrder being returned.', on_delete=django.db.models.deletion.PROTECT, related_name='rma_claims', to='logistics.salesorder')),
            ],
            options={
                'verbose_name': 'RMA Claim',
                'verbose_name_plural': 'RMA Claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['disposition_triage', 'created_at'], name='rma_triage_ts_idx')],
            },
        ),
    ]
