# Generated by Django 6.0.6 on 2026-06-29 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(blank=True, default='', help_text="e.g., 'Box Truck', 'Semi-Trailer', 'Refrigerated Van'.", max_length=50)),
                ('max_payload_kg', models.DecimalField(decimal_places=2, help_text='Maximum cargo weight this vehicle can legally carry.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_volume_m3', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cargo volume in cubic metres.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_hazmat_certified', models.BooleanField(db_index=True, default=False, help_text='If True, this vehicle can carry HAZMAT products. FleetCapacityService checks this before assignment.')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='False when the vehicle is currently on an active route.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_id', models.UUIDField(db_index=True, help_text='UUID of the GlobalUser assigned as driver for this route.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EN_ROUTE', 'En Route'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15)),
                ('planned_date', models.DateField(blank=True, help_text='The date this route is scheduled to execute.', null=True)),
                ('total_payload_kg', models.DecimalField(decimal_places=2, default=0, help_text='Total weight of all cargo on this route.', max_digits=10)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total distance calculated by PostGIS route optimizer.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_routes', to='transportation.vehicle')),
            ],
            options={
                'verbose_name': 'Dispatch Route',
                'verbose_name_plural': 'Dispatch Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_order_id', models.UUIDField(db_index=True, help_text='UUID of the SalesOrder being delivered at this stop.')),
                ('stop_sequence', models.PositiveSmallIntegerField(help_text="The driver's ordered stop number (1 = first stop).")),
                ('delivery_coordinates', models.JSONField(default=dict, help_text='{"lat": 34.0522, "lng": -118.2437}')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=500)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transportation.dispatchroute')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['route', 'stop_sequence'],
                'unique_together': {('route', 'stop_sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='dispatchroute',
            index=models.Index(fields=['status', 'planned_date'], name='route_status_date_idx'),
        ),
    ]
