# Generated by Django 6.0.6 on 2026-06-29 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('QC_FAILED', 'QC Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total PO value. Used by finance.services.encumber_budget().', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by_actor_id', models.UUIDField(blank=True, help_text='UUID of the Admin who transitioned this PO to APPROVED.', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('encumbrance_journal_entry_id', models.UUIDField(blank=True, help_text='UUID of the JournalEntry recording the budget encumbrance.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='po_status_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Agreed unit cost for this line (used for MAC recalculation).', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('qc_passed_qty', models.IntegerField(default=0, help_text='Units that passed QC inspection. These are added to StockLedger.', validators=[django.core.validators.MinValueValidator(0)])),
                ('qc_failed_qty', models.IntegerField(default=0, help_text='Units that failed QC. These are held and routed to returns.', validators=[django.core.validators.MinValueValidator(0)])),
                ('qc_notes', models.CharField(blank=True, default='', help_text='Dock worker notes on why units failed QC.', max_length=500)),
                ('qc_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when dock scanning was completed.', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='inventory.productsku')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Line Item',
                'verbose_name_plural': 'PO Line Items',
                'constraints': [models.CheckConstraint(condition=models.Q(('ordered_qty__gte', 1)), name='po_lineitem_qty_positive')],
            },
        ),
    ]
