# Generated by Django 6.0.6 on 2026-06-30 06:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='polineitem',
            name='po_lineitem_qty_positive',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='po_status_ts_idx',
        ),
        migrations.AlterField(
            model_name='polineitem',
            name='qc_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polineitem',
            name='qc_failed_qty',
            field=models.IntegerField(default=0, help_text='Units that failed quality inspection.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='polineitem',
            name='qc_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='polineitem',
            name='qc_passed_qty',
            field=models.IntegerField(default=0, help_text='Units that passed quality inspection.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='polineitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_by_actor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='encumbrance_journal_entry_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('QC_FAILED', 'QC Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of all line items. Kept in sync by POService.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='notes',
        ),
    ]
