# Generated by Django 6.0.6 on 2026-06-29 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(db_index=True, help_text="Numeric or alphanumeric account code (e.g., '1100', 'AR-USD').", max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], db_index=True, max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot receive new journal lines.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('REVENUE_RECOGNITION', 'Revenue Recognition (Delivery)'), ('BUDGET_ENCUMBRANCE', 'Budget Encumbrance (PO Approved)'), ('ASSET_WRITE_OFF', 'Asset Write-Off (Scrap)'), ('BANK_RECONCILIATION', 'Bank Reconciliation'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], db_index=True, max_length=25)),
                ('reference_module', models.CharField(db_index=True, help_text="Which module triggered this journal entry (e.g., 'logistics').", max_length=30)),
                ('reference_id', models.UUIDField(db_index=True, help_text='UUID of the source document (SalesOrder, PO, RMA, etc.).')),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of the transaction.', max_length=500)),
                ('posted_by_actor_id', models.UUIDField(blank=True, help_text='UUID of the GlobalUser who initiated this journal entry.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_reconciled', models.BooleanField(default=False, help_text='True when BankFeedReconciliation has matched this entry.')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['reference_module', 'reference_id'], name='je_ref_idx'), models.Index(fields=['timestamp'], name='je_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount. Exactly one of debit/credit should be > 0.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount. Exactly one of debit/credit should be > 0.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('memo', models.CharField(blank=True, default='', help_text="Line-level description (e.g., 'Invoice #12345 for SKU-ELEC-001').", max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.chartofaccounts')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
                'constraints': [models.CheckConstraint(condition=models.Q(('debit', 0), ('credit', 0), _connector='OR'), name='journal_line_not_both_debit_and_credit'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='journal_line_at_least_one_nonzero')],
            },
        ),
    ]
